#!/bin/csh
# Do not use -f since it needs initialization when run by cron.

switch ( `uname -n` )
case qsc[0-9]*:
case qscfe[12]:
    set hosttype=qsc
    breaksw
case theta:
case t0[0-9]:
    set hosttype=theta
    breaksw
case lambda:
    set hosttype=lambda
    breaksw
default:
    echo "Unknown system name (`uname -n`).  Aborted."
    exit 1
endsw

cd $HOME/JOBS
/bin/pwd
foreach j (snaptest_hdf5 snaptest_hdf5_1_6 )
    echo $hosttype/subjob $hosttype/$j
    $hosttype/subjob $hosttype/$j
end
