#! /bin/sh
# Cleanup the Daily Test space
# Usauge: DailyHDFTests [-r<version>]
# Example: DailyHDFTests	# test the CVS current version
#	   DailyHDFTests -r1.x	# test version 1.x

# general setup
PROGRAMNAME=`basename $0`
DEBUGMODE=""		# change to -debug for debug mode

# Setup
HOSTNAME=`hostname | cut -f1 -d.`       # no domain part
TODAY=`date +%m%d%a`
H5VER=			# default to current CVS version
H5VERSTR=		# default to current CVS version
TITLE="HDF5 Tests on $TODAY"
errcode=0		# error code so far
CMD=launch		# What command to run. Default to launch.

# Parse command options
while [ $# -gt 0 ]; do
    case "$1" in
	-r*)
	    H5VER="$1"
	    H5VERSTR=_`echo $H5VER | sed -e s/-r// -e s/\\\./_/g`
	    ;;
	-debug*)
	    DEBUGMODE="$1"
	    ;;
	clean)
	    CMD=clean
	    ;;
	report)
	    CMD=report
	    ;;
	launch)
	    CMD=launch
	    ;;
	update)
	    CMD=update
	    ;;
	*)
	    echo "Unknown option ($1)"
	    exit 1
	    ;;
    esac
    shift
done

# Mail addresses for reports
# TOWHOM_PASSED--normal report
# TOWHOM_FAILED--Failure Report
# If in debug mode, email output to myself; else to the "group".
if [ -n "$DEBUGMODE" ]; then
    echo "******** DEBUGMODE is $DEBUGMODE ************"
    TOWHOM_PASSED=acheng@hdfgroup.org
    TOWHOM_FAILED=acheng@hdfgroup.org
else
    TOWHOM_PASSED=asc-passed@hdfgroup.org
    TOWHOM_FAILED=asc-failed@hdfgroup.org
fi

#################################
# Setup test directories
#################################
SNAPYARD=$HOME/snapshots-hdf5${H5VERSTR}
# initial processing of setup option if requested
if [ ! -d ${SNAPYARD} ]; then
    echo "SNAPYARD ($SNAPYARD) does not exist"
    exit 1
fi

LOGDIR=${SNAPYARD}/log
LOGDIRLOCK=${LOGDIR}/.lock-${HOSTNAME}
LOGFILE=${LOGDIR}/${PROGRAMNAME}-${HOSTNAME}_${TODAY}
FAILEDLOG=${LOGDIR}/FAILED_LOG_${TODAY}
FAILEDDETAIL=${LOGDIR}/FAILED_DETAIL_${TODAY}
PASSEDLOG=${LOGDIR}/PASSED_LOG_${TODAY}
SKIPPEDLOG=${LOGDIR}/SKIPPED_LOG_${TODAY}
TIMELOG=${LOGDIR}/TIME_LOG_${TODAY}
REPORTED=${LOGDIR}/REPORTED_${TODAY}
SNAPSHOTLOG=${LOGDIR}/SNAPSHOT_LOG_${TODAY}
RELEASE_ASAP=${SNAPYARD}/release_asap		# make a special release asap
RELEASE_NOT=${SNAPYARD}/release_not		# Do not release
RELEASED=${LOGDIR}/RELEASED_${TODAY}
WATCHERFILE=${SNAPYARD}/watchers		# List of platform watchers
SOURCEDIR=${SNAPYARD}/current			# Source directory
CVSDATE=$SOURCEDIR/src_lastdate			# Date of last source update
TMP_OUTPUT=${LOGDIR}/"#"*.out			# output from different machines

# Setup Mailing command and Report title
MAIL=Mail
TEST_TITLE="$HOSTNAME HDF5${H5VERSTR}_Daily_Tests"

# set up auto-cleanup
trap "rm -f $LOGDIRLOCK" 0
trap "rm -f $LOGDIRLOCK" 1 2 3 4 5 6 7 8 9 10 12 13 14 15

# Execute the command.
case "$CMD" in
    clean)
	# Clean up LOGDIR by moving all files that are not "of today"
	# to OLD.
	# Clean up files older than 10 days in OLD.
	(if cd $LOGDIR; then
	    oldfiles=`find * -type d -prune -o -type f ! -name '*'$TODAY'*' -print`
	    test -n "$oldfiles" && mv $oldfiles OLD/.
	    echo Purging old files
	    find OLD -mtime +21 -print -exec rm '{}' \;
	else
	    echo $LOGDIR not found. Clean command aborted.
	    exit 1
	fi)
	;;
    report)
	# gather up the test results and report it.
	# report result
	# save FAILED or SUCCEESS in REPORTED and remove them
	# Check result
	if [ -f $FAILEDLOG ]; then
	    errcode=1
	    REPORT_TITLE="${TEST_TITLE}_FAILED!!!"
	    TOWHOM=$TOWHOM_FAILED
	else
	    REPORT_TITLE="${TEST_TITLE}"
	    TOWHOM=$TOWHOM_PASSED
	fi
				

	(
	 echo "*** $TITLE $TODAY***"
	 echo "============================="
	 echo "   Tests Summary"
	 echo "============================="
	 xdate="`(test -f $CVSDATE && cat $CVSDATE) || echo Unknown`"
	 echo "Last cvs update: $xdate"
	 if [ -f $FAILEDLOG ]; then
	    sort $FAILEDLOG | tee -a $REPORTED
	    echo ""
	    rm $FAILEDLOG
	 fi
	 if [ -f $SKIPPEDLOG ]; then
	    sort $SKIPPEDLOG | tee -a $REPORTED
	    echo ""
	    rm $SKIPPEDLOG
	 fi
	 if [ -f $PASSEDLOG ]; then
	    sort $PASSEDLOG | tee -a $REPORTED
	    rm $PASSEDLOG
	 fi
	 echo ""
	 echo "============================="
	 echo "   Tests Time Summary"
	 echo "============================="
	 if [ -f $TIMELOG ]; then
	    cat $TIMELOG | tee -a $REPORTED
	    rm $TIMELOG
	 fi
	 if [ -f $FAILEDDETAIL ]; then
	     echo ""
	     echo "============================="
	     echo "   Tests Failures"
	     echo "============================="
	     cat $FAILEDDETAIL
	 fi
	 if [ -n "$TMP_OUTPUT" ]; then
	     echo ""
	     echo "============================="
	     echo "   Tests Details"
	     echo "============================="
	     for f in $TMP_OUTPUT; do
		 echo "========================"
		 echo "   $f"
		 echo "========================"
		cat $f
		rm $f
	     done
	 fi | tee -a $REPORTED
	 echo ""
	) | $MAIL -s "$REPORT_TITLE" $TOWHOM
	;;
    launch)
	LAUNCH_CMD=DailyTest/SubDailytest
	# Make sure at $HOME
	(
	cd
	echo ====================================
	echo "`date` `hostname`"
	echo ====================================
	$LAUNCH_CMD 2>&1
	) >> $HOME/crontab.log
	;;
    update)
	cd $SOURCEDIR
	cvs update -Pd 
	date > $CVSDATE
	;;
    *)
	echo "Unknown Command ($CMD)"
	exit 1
	;;
esac

if [ -f $LOGFILE ]; then
    if [ -n "$DEBUGMODE" ]; then
	echo "$LOGFILE exists.  No more daily tests today"
    fi
    exit 1
fi

#
if [ -n "$DEBUGMODE" ]; then
    echo "launching runsnap ..."
fi

# setup from which version of source to launch test
if [ -z "$H5VERSTR" ]; then
    H5SRC_VER=current
else
    H5SRC_VER=v$H5VERSTR
fi

# final exit
exit $errcode
