#!/bin/csh
# Do not use -f since it needs initialization when run by cron.

switch ( `uname -n` )
case pink.lanl.gov:
case pfe[12].lanl.gov:
    set hosttype=pink
    breaksw
case ffe[12].lanl.gov:
    set hosttype=flash
    breaksw
case qsc[0-9]*:
case qscfe[12]:
    set hosttype=qsc
    breaksw
case theta:
case t0[0-9]:
    set hosttype=theta
    breaksw
case lambda:
    set hosttype=lambda
    breaksw
default:
    echo "Unknown system name (`uname -n`).  Aborted."
    exit 1
endsw

cd $HOME/JOBS
set echo
# run one snaptest at a time so that parallel tests won't conflict.
# Can run multiple parallel jobs since each specifies its own $HDF5_PARAPREFIX.
set depend=""
foreach job (snaptest_hdf5 snaptest_hdf5_1_6)
    subjob $job -J ${job}_$hosttype $depend
#    set depend="-w ended($job)"
end
