#! /bin/sh
#bsub -q smallq -n 4 -o out4 -W 10 prun -t -n 4 -N 1 basicScaleF.exe  100000 1
#bsub -q threadq -o $taskname.$nproc.$today.$$ -W $job_time $* $task

nproc=4
myemail=acheng@ncsa.uiuc.edu
extra_option=

# Default job_time is 2 hours.
# flash is slow and need more time.  
# qsc's Testdir disks are slow, need more time.
# qsc's Testdir disks are much faster now.  Need normal time.
# flash: can only use largeq, longq. Use longq which is less crowded.
# Stopped asking for longq since it is crowded.
case `hostname` in
    ffe*)
	job_time=180	# 3 hours
	#extra_option="-q longq"
	;;
    *)
	job_time=120	# 2 hours
	;;
esac

task=$1
taskname=`basename $task`
shift

bsub -n $nproc -W $job_time -u $myemail $extra_option $* $task
bjobs
