#!/bin/tcsh
#  Sample Batch Script (minimal) for a CUDA job
#
# $HOME/.soft contains:
#
#  +cuda
#  +nvidia-sdk
#  +intel-10.1.017
#  +hdf5-1.8.2
#  @teragrid-basic
#  @globus-4.0
#  @teragrid-dev
#
#  Submit this script using the command: qsub -q lincoln <script_name>
#
#  Use the "qstat" command to check the status of a job.
#
# The following are embedded QSUB options. The syntax is #PBS (the # does
# _not_  denote that the lines are commented out so do not remove).
#
# walltime : maximum wall clock time (hh:mm:ss)
#PBS -l walltime=0:05:00
#
# nodes: number of 8-core nodes
#   ppn: how many cores per node to use (1 through 8)
#       (you are always charged for the entire node)
#PBS -l nodes=1:ppn=8
#
# export all my environment variables to the job
#PBS -V
#
# job name (default = name of script file)
#PBS -N hdfMatMul
#
#
# filename for standard output (default = <job_name>.o<job_id>)
# at end of job, it is in directory from which qsub was executed
# remove extra ## from the line below if you want to name your own file
###PBS -o testjob.out
#
# filename for standard error (default = <job_name>.e<job_id>)
# at end of job, it is in directory from which qsub was executed
# remove extra ## from the line below if you want to name your own file
###PBS -e testjob.err
#
# End of embedded QSUB options
#
# set echo               # echo commands before execution; use for debugging
#

#cd $SCR                # change to job scratch directory, 
                       # use cdjob <jobid> to go to this directory once
                       # the job has started
cd $HOME

./a.out

