#! /bin/sh
# Submit daily tests of HDF4 base software
# Usauge: DailyHDFTests [-r<version>]
# Example: DailyHDFTests	# test the CVS current version
#	   DailyHDFTests -r1.2	# test version 1.2
#	   DailyHDFTests -r1.4	# test version 1.4

# general setup
PROGRAMNAME=`basename $0`
DEBUGMODE=""		# change to -debug for debug mode

# Setup
HOSTNAME=`hostname | cut -f1 -d.`       # no domain part
TODAY=`date +%y%m%d`
SW=HDF4			# Name of Software.
sw=hdf4			# Name of Software in lower cases.
SWVER=			# Software version, default to current CVS version.
SWVERSTR=		# Software version string.
TITLE="${SW} Tests on $TODAY"
errcode=0		# error code so far

# Parse command options
while [ $# -gt 0 ]; do
    case "$1" in
	-r*)
	    SWVER="$1"
	    SWVERSTR=_`echo $SWVER | sed -e s/-r// -e s/\\\./_/g`
	    ;;
	-debug*)
	    DEBUGMODE="$1"
	    ;;
	*)
	    echo "Unknown option ($1)"
	    exit 1
	    ;;
    esac
    shift
done

# Mail addresses for reports
# TOWHOM_PASSED--normal report
# TOWHOM_FAILED--Failure Report
# If in debug mode, email output to myself; else to the "group".
if [ -n "$DEBUGMODE" ]; then
    echo "******** DEBUGMODE is $DEBUGMODE ************"
    TOWHOM_PASSED=acheng
    TOWHOM_FAILED=acheng
else
    TOWHOM_PASSED="hdf-cvs@hdfgroup.org hdf5svn@hdfgroup.org"
    TOWHOM_FAILED=hdf4lib@hdfgroup.org
fi

# Setup test directories
LOGDIR=$HOME/snapshots-${sw}${SWVERSTR}/log
LOGDIRLOCK=${LOGDIR}/.lock-${HOSTNAME}
LOGFILE=${LOGDIR}/${PROGRAMNAME}-${HOSTNAME}_${TODAY}
FAILEDLOG=${LOGDIR}/FAILED_LOG_${TODAY}
FAILEDDETAIL=${LOGDIR}/FAILED_DETAIL_${TODAY}
PASSEDLOG=${LOGDIR}/PASSED_LOG_${TODAY}
SKIPPEDLOG=${LOGDIR}/SKIPPED_LOG_${TODAY}
TIMELOG=${LOGDIR}/TIME_LOG_${TODAY}
REPORTED=${LOGDIR}/REPORTED_${TODAY}
SNAPSHOTLOG=${LOGDIR}/SNAPSHOT_LOG_${TODAY}
RELEASE_ASAP=${LOGDIR}/../release_asap		# make a special release asap
RELEASE_ALWAYS=${LOGDIR}/../release_always	# always release
RELEASE_NOT=${LOGDIR}/../release_not		# Do not release
RELEASED=${LOGDIR}/RELEASED_${TODAY}
WATCHERFILE=${LOGDIR}/../watchers		# List of platform watchers
CMD="bin/runtest $DEBUGMODE ${SWVER}"

# Setup Mailing command and Report title
if [ $HOSTNAME = gondolin ]; then
    MAIL=Mail
    TEST_TITLE="$HOSTNAME ${SW}${SWVERSTR}_Daily_Tests"
else
    MAIL=mail
    TEST_TITLE="${SW}${SWVERSTR}_Daily_Tests"
fi

# set up auto-cleanup
trap "rm -f $LOGDIRLOCK" 0
trap "rm -f $LOGDIRLOCK" 1 2 3 4 5 6 7 8 9 10 12 13 14 15

if [ $HOSTNAME != gondolin ]; then
# Clean up LOGDIR by moving all files that are not "of today" to OLD.
# Then go into OLD and move all files older than 7 days to OLDER.
# Then go into OLDer and remove all files older than 30 days.
# This procedure keeps old logfiles in two tiers.  The first tier is OLD
# which should be in AFS space so that the files are available to most hosts.
# The second tier is OLDER which could be in HDF's own NFS space which has
# much bigger capacity but not as widely available.
(   
    nold=6
    nolder=31
    echo cleaning $LOGDIR by moving all old logfiles to OLD
    cd $LOGDIR
    test -d OLD/. || mkdir OLD
    find . \( -name OLD -prune \) \
	-o -type f ! -name '*'$TODAY'*' -exec mv '{}' OLD/. \;

    echo cleaning $LOGDIR/OLD by moving all files older than $nold days to OLDER
    cd OLD
    test -d OLDER/. || mkdir OLDER
    find . \( -name OLDER -prune \) \
	-o -type f -mtime +$nold -exec mv '{}' OLDER/. \;

    echo cleaning $LOGDIR/OLDER by removing all files older than $nolder days.
    cd OLDER
    find . -type f -mtime +$nolder -exec rm -f '{}' \;
)
fi

if [ -f $LOGFILE ]; then
    if [ -n "$DEBUGMODE" ]; then
	echo "$LOGFILE exists.  No more daily tests today"
    fi
    exit 1
fi

# set up the lock file
# if one already exists, just show it and continues
if [ -f $LOGDIRLOCK ]; then
    echo "LOGDIRLOCK($LOGDIRLOCK) exists. Content is:"
    cat $LOGDIRLOCK
fi
date > $LOGDIRLOCK
echo PID@HOSTNAME=$$@$HOSTNAME >> $LOGDIRLOCK

#
if [ -n "$DEBUGMODE" ]; then
    echo "launching runsnap ..."
fi

# setup from which version of source to launch test
if [ -z "$SWVERSTR" ]; then
    SWSRC_VER=current
else
    SWSRC_VER=v$SWVERSTR
fi

if [ $HOSTNAME != gondolin ]; then
    (cd $HOME/${SW}/${SWSRC_VER}/${sw}; $CMD -all) > $LOGFILE 2>&1
else
    (cd $HOME/${SW}/${SWSRC_VER}/${sw}; $CMD -nocvs) > $LOGFILE 2>&1
fi

# Verify test script did complete by checking the last lines
(tail -4 $LOGFILE | grep -s "^*** finished .* in $HOSTNAME ***" > /dev/null 2>&1) ||
    (echo "****snaptest launcher FAILED to complete in $HOSTNAME****" >> $FAILEDLOG)

# Check result
if [ -f $FAILEDLOG ]; then
    errcode=1
    REPORT_TITLE="${TEST_TITLE}_FAILED!!!"
    TOWHOM=$TOWHOM_FAILED
else
    REPORT_TITLE="${TEST_TITLE}"
    TOWHOM=$TOWHOM_PASSED
fi
    
# report result
# save FAILED or SUCCEESS in REPORTED and remove them
(
 echo "*** $TITLE ***"
 echo "============================="
 echo "   Tests Summary"
 echo "============================="
 if [ -f $FAILEDLOG ]; then
    sort $FAILEDLOG | tee -a $REPORTED
    rm $FAILEDLOG
 fi
 if [ -f $SKIPPEDLOG ]; then
    sort $SKIPPEDLOG | tee -a $REPORTED
    echo ""
    rm $SKIPPEDLOG
 fi
 if [ -f $PASSEDLOG ]; then
    sort $PASSEDLOG | tee -a $REPORTED
    rm $PASSEDLOG
 fi
 echo ""
 echo "============================="
 echo "   Tests Time Summary"
 echo "============================="
 if [ -f $TIMELOG ]; then
    cat $TIMELOG | tee -a $REPORTED
    rm $TIMELOG
 fi
 # If failures detected, show failed details, watchers list and test details.
 # Else just show test details file name.
 if [ -f $FAILEDDETAIL ]; then
    echo ""
    echo "============================="
    echo "   Tests Failures"
    echo "============================="
    cat $FAILEDDETAIL | tee -a $REPORTED
    rm $FAILEDDETAIL
    echo ""
    echo "============================="
    echo "   Watchers List"
    echo "============================="
    cat $WATCHERFILE
    echo ""
    echo "============================="
    echo "   Tests Details"
    echo "============================="
    cat $LOGFILE
 else
    echo "============================="
    echo "   Tests Details"
    echo "============================="
    echo "See $LOGFILE"
 fi
) | $MAIL -s "$REPORT_TITLE" $TOWHOM

# see if any real tests occurred
if grep -s "^NO TEST:" $REPORTED > /dev/null; then
    tests_done="none"
fi

# remove lock
rm $LOGDIRLOCK

if [ $HOSTNAME != gondolin ]; then
# do a snapshot release if
#   test-passed && 
#   release_not-is-not-present &&
#   ( today-is-Sunday || release_asap-is-present || release_always-is-present)
# The difference between release_asap and release_always is that release_asap
# is a one time deal and needs to be set again if desire; while release_always
# stays in effect until removed.
if [ $errcode -eq 0 -a x-$tests_done != x-none -a \
    ! -f $RELEASE_NOT -a \
    \( `date +%a` = Sun -o -f $RELEASE_ASAP -o -f $RELEASE_ALWAYS \) ]; then
    # do a snapshot.
    SWDIR=$HOME/${SW}/current/${sw}
    if [ -f $RELEASE_ASAP ]; then
	RELEASE_MESG="Special snapshot release launched for ${SW}${SWVERSTR}."
    elif [ -f $RELEASE_ALWAYS ]; then
	RELEASE_MESG="Snapshot release launched for ${SW}${SWVERSTR}."
    else
	RELEASE_MESG="Weekly snapshot release launched for ${SW}${SWVERSTR}."
    fi

    # Before doing the release, check if there are some daily tests in progress.
    # If so, wait for them to finish (up to 30 minutes).  Then proceed.
    wait_max=30
    lockfiles=`ls $LOGDIR/.lock-* 2>/dev/null`
    while [ -n "$lockfiles" -a $wait_max -gt 0 ] ; do
	echo $lockfiles exist.  Wait a minute.
	sleep 60
	wait_max=`expr $wait_max - 1`
	lockfiles=`ls $LOGDIR/.lock-* 2>/dev/null`
    done
    (
	cd $SWDIR
	bin/snapshot
    ) >> $SNAPSHOTLOG 2>&1
    errcode=$?

    # if snapshot went okay, remove release-asap-request
    if [ $errcode -eq 0 ]; then
	if [ -f $RELEASE_ASAP ]; then
	    mv $RELEASE_ASAP $RELEASED
	else
	    touch $RELEASED
	fi
	RELEASE_Result="Released"
	TOWHOM=$TOWHOM_PASSED
    else
	RELEASE_Result="FAILED"
	TOWHOM=$TOWHOM_FAILED
    fi

    # report snapshot result
    (
     echo $RELEASE_MESG
     echo "$RELEASE_Result with exit Error Code = ${errcode}."
     echo "Complete output is stored in"
     echo "    $SNAPSHOTLOG"
    ) |
    mail -s "${SW}${SWVERSTR}_snapshot:$RELEASE_Result" $TOWHOM
fi
fi


# final exit
exit $errcode
