#! /bin/sh
# Submit daily tests of HDF5 base software
# Usauge: DailyHDFTests [-r<version>]
# Example: DailyHDFTests	# test the CVS current version
#	   DailyHDFTests -r1.2	# test version 1.2

# general setup
PROGRAMNAME=`basename $0`
DEBUGMODE=""
test -n "$DEBUGMODE" && echo "******** DEBUGMODE is $DEBUGMODE ************"

# Email any messages to whom
TOWHOM=${DEBUGMODE:+acheng}
TOWHOM=${TOWHOM:-hdf5cvs@ncsa.uiuc.edu}

# Setup
HOSTNAME=`hostname | sed -e s/.ncsa.uiuc.edu//`
TODAY=`date +%y%m%d`
H5VER=			# default to current CVS version
H5VERSTR=		# default to current CVS version
errcode=0		# error code so far

# Parse command options
while [ $# -gt 0 ]; do
    case "$1" in
	-r*)
	    H5VER="$1"
	    H5VERSTR=_`echo $H5VER | sed -e s/-r// -e s/\\\./_/g`
	    ;;
	*)
	    echo "Unknown option ($1)"
	    exit 1
	    ;;
    esac
    shift
done

# Setup test directories
LOGDIR=$HOME/snapshots-hdf5${H5VERSTR}/log
LOGDIRLOCK=${LOGDIR}/.lock
LOGFILE=${LOGDIR}/${PROGRAMNAME}_${TODAY}
FAILEDLOG=${LOGDIR}/FAILED_LOG_${TODAY}
SNAPSHOTLOG=${LOGDIR}/SNAPSHOT_LOG_${TODAY}
CMD="$HOME/bin-sys/runsnap ${H5VER}"

# set up auto-cleanup
trap "rm -f $LOGDIRLOCK" 0

# Clean up LOGDIR by moving all files that are not "of today"
# to OLD.
(   
    cd $LOGDIR
    oldfiles=`find * -type d -prune -o -type f ! -name '*'$TODAY -print`
    test -n "$oldfiles" && mv $oldfiles OLD/.
)

if [ -f $LOGFILE ]; then
    if [ -n "$DEBUGMODE" ]; then
	echo "$LOGFILE exists.  No more daily tests today"
    fi
    exit 1
fi

#
if [ -n "$DEBUGMODE" ]; then
    echo "launching runsnap ..."
fi

$CMD -all > $LOGFILE 2>&1

# Check result
if [ -f $FAILEDLOG ]; then
    errcode=1
fi
    
# report result
if [ $errcode -eq 0 ]; then
    (echo "No failures reported"
     echo ""
     echo "============================="
     echo "   All Tests Results"
     echo "============================="
     cat $LOGFILE) |
    mail -s "HDF5${H5VERSTR}_Daily_Tests" $TOWHOM
else
    # some hosts have failed the tests
    ( cat $FAILEDLOG
     echo ""
     echo "============================="
     echo "   All Tests Results"
     echo "============================="
     cat $LOGFILE) |
    mail -s "HDF5${H5VERSTR}_Daily_Tests_FAILED!!!" $TOWHOM
fi

# do a snapshot release if
# test-succeeded && today-is-saturday
if [ $errcode -eq 0 -a `date +%w` -eq 6 ]; then
    # do a snapshot.  Default to version 1.3
    H5DIR=$HOME/HDF5/v${H5VERSTR:-_1_3}/hdf5
    (
	cd $H5DIR
	bin/snapshot
    ) >> $SNAPSHOTLOG 2>&1
    errcode=$?

    # report snapshot result
    (
     echo "Weekly Snapshot launched for HDF5${H5VERSTR}."
     echo "Exit Error Code = ${errcode}."
     echo "Complete output is stored in"
     echo "    $SNAPSHOTLOG"
    ) |
    mail -s "HDF5${H5VERSTR}_snapshot" $TOWHOM
fi


# final exit
exit $errcode
